"""Remove pattern type table

Revision ID: 0417230df4f5
Revises: 064d375308b1
Create Date: 2024-04-26 16:12:00.285525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0417230df4f5'
down_revision = '064d375308b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('txpattern', schema=None) as batch_op:
        batch_op.drop_constraint(
            'txpattern_pattern_type_id_fkey', type_='foreignkey')
        batch_op.drop_column('pattern_type_id')
    op.drop_table('txpatterntype')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('txpattern', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pattern_type_id',
                            sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('txpattern_pattern_type_id_fkey',
                                    'txpatterntype', [
                                        'pattern_type_id'], ['id'])

    op.create_table('txpatterntype',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('pattern_type', sa.VARCHAR(length=50),
                              autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='txpatterntype_pkey'),
                    sa.UniqueConstraint(
                        'pattern_type', name='txpatterntype_pattern_type_key')
                    )
    # ### end Alembic commands ###
