"""Add string-based pattern type column

Revision ID: 064d375308b1
Revises: 8dde05ed9135
Create Date: 2024-04-26 16:09:55.980408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '064d375308b1'
down_revision = '8dde05ed9135'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('txpattern', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('pattern_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('txpattern', schema=None) as batch_op:
        batch_op.drop_column('pattern_type')

    # ### end Alembic commands ###
