"""Add email_lower to user

Revision ID: 09f229d79915
Revises: 0417230df4f5
Create Date: 2024-08-11 21:45:36.718901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09f229d79915'
down_revision = '0417230df4f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('txuser', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_lower', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['email_lower'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('txuser', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('email_lower')

    # ### end Alembic commands ###
