"""Remove obsolete txgrouppattern table

Revision ID: 8dde05ed9135
Revises: cfa61cffb285
Create Date: 2024-04-26 15:00:33.477256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dde05ed9135'
down_revision = 'cfa61cffb285'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('txgrouppattern')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('txgrouppattern',
                    sa.Column(
                        'group',
                        sa.INTEGER(),
                        autoincrement=False,
                        nullable=False,
                    ),
                    sa.Column(
                        'pattern',
                        sa.INTEGER(),
                        autoincrement=False,
                        nullable=False,
                    ),
                    sa.ForeignKeyConstraint(
                        ['group'],
                        ['txgroup.id'],
                        name='txgrouppattern_group_fkey',
                    ),
                    sa.ForeignKeyConstraint(
                        ['pattern'],
                        ['txpattern.id'],
                        name='txgrouppattern_pattern_fkey',
                    ),
                    sa.PrimaryKeyConstraint(
                        'group',
                        'pattern',
                        name='txgrouppattern_pkey',
                    )
                    )
    # ### end Alembic commands ###
