"""Add memberships and assignments

Revision ID: cfa61cffb285
Revises: 0279ac947826
Create Date: 2024-04-26 14:53:29.932670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfa61cffb285'
down_revision = '0279ac947826'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('txmembership',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('group_id', sa.Integer(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('role', sa.String(length=10), nullable=True),
                    sa.Column('state', sa.String(length=10), nullable=True),
                    sa.ForeignKeyConstraint(['group_id'], ['txgroup.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['txuser.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('txassignment',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('group_id', sa.Integer(), nullable=True),
                    sa.Column('pattern_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['group_id'], ['txgroup.id'], ),
                    sa.ForeignKeyConstraint(
                        ['pattern_id'], ['txpattern.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_table('txusergroupinvite')
    op.drop_table('txusergroup')
    with op.batch_alter_table('txgroup', schema=None) as batch_op:
        batch_op.drop_constraint('txgroup_owner_id_fkey', type_='foreignkey')
        batch_op.drop_column('owner_id')

    with op.batch_alter_table('txuser', schema=None) as batch_op:
        batch_op.add_column(sa.Column('block_invitations',
                            sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('txuser', schema=None) as batch_op:
        batch_op.drop_column('block_invitations')

    with op.batch_alter_table('txgroup', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('owner_id', sa.INTEGER(),
                      autoincrement=False, nullable=True))
        batch_op.create_foreign_key(
            'txgroup_owner_id_fkey', 'txuser', ['owner_id'], ['id'])

    op.create_table('txusergroup',
                    sa.Column('user', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('group', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(
                        ['group'], ['txgroup.id'],
                        name='txusergroup_group_fkey'),
                    sa.ForeignKeyConstraint(['user'], ['txuser.id'],
                                            name='txusergroup_user_fkey'),
                    sa.PrimaryKeyConstraint(
                        'user', 'group', name='txusergroup_pkey')
                    )
    op.create_table('txusergroupinvite',
                    sa.Column('user', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('group', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(
                        ['group'], ['txgroup.id'],
                        name='txusergroupinvite_group_fkey'),
                    sa.ForeignKeyConstraint(
                        ['user'], ['txuser.id'],
                        name='txusergroupinvite_user_fkey'),
                    sa.PrimaryKeyConstraint(
                        'user', 'group', name='txusergroupinvite_pkey')
                    )
    op.drop_table('txassignment')
    op.drop_table('txmembership')
    # ### end Alembic commands ###
