"""Add user date fields

Revision ID: fd944d6ead69
Revises: 09f229d79915
Create Date: 2024-08-17 10:53:20.753751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd944d6ead69'
down_revision = '09f229d79915'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('txuser', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('verify_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('access_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('txuser', schema=None) as batch_op:
        batch_op.drop_column('access_date')
        batch_op.drop_column('verify_date')
        batch_op.drop_column('create_date')

    # ### end Alembic commands ###
